import os
import sys
import streamlit as st
import pandas as pd

# -------------------------------------------------
# Allow imports from project root
# -------------------------------------------------

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.append(ROOT_DIR)

from app.predict import predict_image
from app.database import (
    save_prediction,
    get_history,
    delete_history
)
from app.llm import generate_medical_report
from app.utils import save_uploaded_file
from app.report_generator import generate_pdf_report

# -------------------------------------------------
# Streamlit Config
# -------------------------------------------------

st.set_page_config(
    page_title="AI Medical Report Assistant",
    page_icon="🩺",
    layout="wide"
)

st.title("🩺 AI Medical Report Assistant")

st.markdown(
"""
Upload a Chest X-Ray image and let AI predict whether
the image is **NORMAL** or **PNEUMONIA**.

The system will:

- Predict disease
- Show confidence score
- Generate an AI-assisted medical report
- Save prediction history
"""
)

st.divider()

# -------------------------------------------------
# Sidebar
# -------------------------------------------------

st.sidebar.title("About")

st.sidebar.info(
"""
Deep Learning Model:
EfficientNetB0

Database:
SQLite

LLM:
Google Gemini

Framework:
Streamlit
"""
)

# -------------------------------------------------
# Upload Image
# -------------------------------------------------

uploaded_file = st.file_uploader(
    "Upload Chest X-Ray Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    st.subheader("Uploaded Image")

    st.image(uploaded_file, width=350)

    file_path = save_uploaded_file(uploaded_file)

    if st.button("Predict Disease"):

        with st.spinner("Analyzing Image..."):

            prediction, confidence = predict_image(file_path)

        st.success("Prediction Completed")

        col1, col2 = st.columns(2)

        with col1:

            st.metric(
                "Prediction",
                prediction
            )

        with col2:

            st.metric(
                "Confidence",
                f"{confidence:.2f}%"
            )

        st.divider()

        st.subheader("AI Medical Report")

        with st.spinner("Generating Report..."):

            report = generate_medical_report(
                prediction,
                confidence
            )

        # Create PDF report
        pdf_path = generate_pdf_report(
            uploaded_file.name,
            prediction,
            confidence,
            report
        )

        st.success("Report Generated Successfully")

        st.markdown(report)

        # Download button
        with open(pdf_path, "rb") as pdf_file:
        
            st.download_button(
                label="📄 Download PDF Report",
                data=pdf_file,
                file_name=os.path.basename(pdf_path),
                mime="application/pdf"
            )

        formatted_report = f"""
        Prediction: {prediction}

        Confidence: {confidence:.2f}%

        AI Medical Report:
        {report}
        """

        save_prediction(
            uploaded_file.name,
            prediction,
            confidence,
            formatted_report
        )

        st.success("Prediction Saved Successfully")

st.divider()

st.header("Prediction History")
# -------------------------------------------------
# Load History
# -------------------------------------------------

history = get_history()

if len(history) == 0:

    st.info("No prediction history available.")

else:

    df = pd.DataFrame(
        history,
        columns=[
            "ID",
            "Image Name",
            "Prediction",
            "Confidence (%)",
            "AI Report",
            "Timestamp"
        ]
    )

    st.dataframe(
        df,
        use_container_width=True,
        hide_index=True
    )

    st.download_button(
        label="Download Prediction History (CSV)",
        data=df.to_csv(index=False),
        file_name="prediction_history.csv",
        mime="text/csv"
    )

st.divider()

# -------------------------------------------------
# Clear History
# -------------------------------------------------

st.subheader("Database Management")

if st.button("Clear Prediction History"):

    delete_history()

    st.success("Prediction history deleted successfully.")

    st.rerun()

st.divider()

# -------------------------------------------------
# Footer
# -------------------------------------------------

st.markdown("---")

st.markdown(
"""
### Disclaimer

This application is intended **only for educational and demonstration purposes**.

The prediction is generated by a deep learning model trained on a public dataset.
The AI-generated report is created using a Large Language Model (LLM) and **must not**
be considered a medical diagnosis.

Always consult a qualified healthcare professional for medical advice,
diagnosis, and treatment.
"""
)